### ISSUE TITLE
It should also unload image from memory

### ISSUE THREAD

**Issue by kozusznik** [PetrBainar/scijava-parallel#2]
https://github.com/PetrBainar/scijava-parallel/blob/2c393d66f8561eb189b19f68dcad326bfc688708/src/main/java/cz/it4i/parallel/LocalPluginWorker.java#L59

**Comment by PetrBainar** [comment]
@kozusznik Is this still an issue or was it already resolved?

**Comment by kozusznik** [comment]
It is not issue.
